# Generated by Django 4.0.4 on 2022-06-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Adresse', models.CharField(max_length=255, null=True)),
                ('PLZ', models.CharField(max_length=5, null=True)),
                ('Ort', models.CharField(max_length=50, null=True)),
                ('Telefonnummer', models.CharField(max_length=50, null=True)),
                ('eMail', models.CharField(max_length=255, null=True)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pflanze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Gattung', models.CharField(max_length=50, null=True)),
                ('Pflegehinweis', models.CharField(max_length=255, null=True)),
                ('Picture', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Beschreibung', models.CharField(max_length=255, null=True)),
                ('Pflegetrupp', models.CharField(max_length=50, null=True)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Beschreibung', models.CharField(max_length=255, null=True)),
                ('Adresse', models.CharField(max_length=255, null=True)),
                ('PLZ', models.CharField(max_length=5, null=True)),
                ('Ort', models.CharField(max_length=50, null=True)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('Status', models.BooleanField()),
                ('KundenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Wasergeange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField()),
                ('Standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.standort')),
            ],
        ),
        migrations.CreateModel(
            name='Standort_Pflanze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anzahl', models.IntegerField(null=True)),
                ('Freitext', models.CharField(max_length=255, null=True)),
                ('Pflanze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.pflanze')),
                ('Standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.standort')),
            ],
        ),
        migrations.CreateModel(
            name='Route_Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freitext', models.CharField(max_length=255, null=True)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.route')),
                ('Standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.standort')),
            ],
        ),
        migrations.CreateModel(
            name='Pflegegaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField()),
                ('Standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citygruen.standort')),
            ],
        ),
    ]
